"""empty message

Revision ID: 5c86f0a75783
Revises: 
Create Date: 2020-06-08 15:25:04.181095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c86f0a75783'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('last_online', sa.DateTime(), nullable=False),
    sa.Column('num_searches', sa.Integer(), nullable=False),
    sa.Column('last_searched', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('access', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wbso',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nr', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('path', sa.TEXT(), nullable=True),
    sa.Column('bedrijf', sa.TEXT(), nullable=True),
    sa.Column('jaar', sa.BigInteger(), nullable=True),
    sa.Column('zwaartepunt', sa.TEXT(), nullable=True),
    sa.Column('opdrachtgever', sa.TEXT(), nullable=True),
    sa.Column('full_text', sa.TEXT(), nullable=True),
    sa.Column('aanleiding', sa.TEXT(), nullable=True),
    sa.Column('t_knel', sa.TEXT(), nullable=True),
    sa.Column('opl', sa.TEXT(), nullable=True),
    sa.Column('prog', sa.TEXT(), nullable=True),
    sa.Column('nieuw', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('zwaartepunt', sa.TEXT(), nullable=True),
    sa.Column('key_terms', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=False)
    op.create_table('search_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['search_query.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('bedrijf', sa.String(), nullable=True),
    sa.Column('jaar', sa.Integer(), nullable=True),
    sa.Column('zwaartepunt', sa.String(), nullable=True),
    sa.Column('opdrachtgever', sa.String(), nullable=True),
    sa.Column('full_text', sa.TEXT(), nullable=True),
    sa.Column('aanleiding', sa.TEXT(), nullable=True),
    sa.Column('t_knel', sa.TEXT(), nullable=True),
    sa.Column('opl', sa.TEXT(), nullable=True),
    sa.Column('prog', sa.TEXT(), nullable=True),
    sa.Column('nieuw', sa.TEXT(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.Column('search_collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['search_collection_id'], ['search_collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_result')
    op.drop_table('search_collection')
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_table('task')
    op.drop_table('search_query')
    op.drop_table('wbso')
    op.drop_table('user')
    # ### end Alembic commands ###
