"""update search query

Revision ID: 7c8a3420a55c
Revises: 5c86f0a75783
Create Date: 2020-06-29 17:12:05.140659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8a3420a55c'
down_revision = '5c86f0a75783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_query', sa.Column('aanleiding', sa.TEXT(), nullable=True))
    op.add_column('search_query', sa.Column('opl', sa.TEXT(), nullable=True))
    op.add_column('search_query', sa.Column('prog', sa.TEXT(), nullable=True))
    op.add_column('search_query', sa.Column('t_knel', sa.TEXT(), nullable=True))
    op.add_column('search_query', sa.Column('t_nieuw', sa.TEXT(), nullable=True))

    # Set default values of new columns to 'x'
    op.execute("UPDATE search_query SET aanleiding= 'x'")
    op.execute("UPDATE search_query SET opl= 'x'")
    op.execute("UPDATE search_query SET prog= 'x'")
    op.execute("UPDATE search_query SET t_knel= 'x'")
    op.execute("UPDATE search_query SET t_nieuw= 'x'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_query', 't_nieuw')
    op.drop_column('search_query', 't_knel')
    op.drop_column('search_query', 'prog')
    op.drop_column('search_query', 'opl')
    op.drop_column('search_query', 'aanleiding')
    # ### end Alembic commands ###
